# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'basics'
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: npm ci
    - name: Test
      run: npm test
  docker-build-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'basics'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: basics
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: ls -la
    - name: Build image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/actions2:latest .
    - name: Push image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/actions2:latest
